OuEstMonCamion/Models/ErrorViewModel.cs
using System;

namespace OuEstMonCamion.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OuEstMonCamion/Models/GpsCoordModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OuEstMonCamion.Models
{
    public class GpsCoordModel
    {
        public string longitude { get; set; }
        public string latitude { get; set; }
        public DateTime date { get; set; }
    }
}

OuEstMonCamion/Models/TruckModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OuEstMonCamion.Models
{
    public class TruckModel
    {
        [Display(Name = "Identifiant Camion")]
        [DataType(DataType.Text)]
        public string RequestId { get; set; }

        public string Id { get; set; }

        [Display(Name = "Emplacement")]
        public string Emplacement { get; set; }
        

        public GpsCoordModel DerniereGeo { get; set; }

        [Display(Name = "Couleur")]
        public string Couleur { get; set; }
        

        public bool detail { get; set; }

        #region moduleGPS
        [Display(Name = "Niveau de batterie")]
        public string NiveaudeBatterie { get; set; }
        public string FirmwareVersion { get; set; }
        public List<GpsCoordModel> GpsCoords { get; set; }
        #endregion

        
    }
}

OuEstMonCamion/ViewModels/TruckFindViewModel.cs
using OuEstMonCamion.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OuEstMonCamion.ViewModels
{
    public class TruckFindViewModel
    {
        public List<TruckModel> Trucks {get; set;}

        [Display(Name = "Couleur")]
        public string couleur { get; set; }

    }
}

OuEstMonCamion/Controllers/FindTruckController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OuEstMonCamion.Models;
using OuEstMonCamion.Service;
using OuEstMonCamion.ViewModels;

namespace OuEstMonCamion.Controllers
{
    public class FindTruckController : Controller
    {
        private readonly ITruckService _truckService;

        public FindTruckController(ITruckService truckService)
        {
            _truckService = truckService;
        }
        // GET: FindTruck
        public ActionResult Index()
        {
            TruckModel tm = new TruckModel();
            return View(tm);
        }
        
        public ActionResult Details()
        {
            TruckFindViewModel tm = new TruckFindViewModel();
            return View(tm);
        }

        [HttpPost]
        public ActionResult Details(TruckFindViewModel trucksvm)
        {
            try
            {

                List<TruckModel> trucks = _truckService.GetTrucks();
                var trucksToDisplay = trucks.Where(x => x.Couleur.ToLower() == trucksvm.couleur.ToLower()).ToList();
                trucksvm.Trucks = trucksToDisplay;
                foreach (var truck in trucksvm.Trucks)
                {
                    truck.DerniereGeo = truck.GpsCoords.OrderByDescending(x => x.date).FirstOrDefault();
                }
                return View(trucksvm);
            }
            catch (Exception)
            {
                return View(trucksvm);
            }
        }
        [HttpPost]
        public ActionResult Index(TruckModel truck)
        {
            try
            {

                List<TruckModel> trucks = _truckService.GetTrucks();
                string id = truck.RequestId;

                var truckToDisplay = trucks.FirstOrDefault(x => x.Id == truck.RequestId);
                truckToDisplay.DerniereGeo = truckToDisplay.GpsCoords.OrderByDescending(x => x.date).FirstOrDefault();
                truckToDisplay.detail = truck.detail;
                return View(truckToDisplay);

            }
            catch (Exception)
            {
                return View(truck);
            }
        }
    }
}

OuEstMonCamion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OuEstMonCamion.Models;

namespace OuEstMonCamion.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OuEstMonCamion/Views/FindTruck/Details.cshtml
@model OuEstMonCamion.ViewModels.TruckFindViewModel
@{
    ViewData["Title"] = "Recherche détaillée";
    int imarker = 0;
    int zoom = 19;
}

<br />
<br />
<br />
<br />
<div class="row " style="margin-left : 12px;">
    <div class="col-md-2">
        <h1>Critères...</h1>
        <br />
        <form asp-action="Details" method="post">
            <div class="form-group">
                <label asp-for="couleur"></label>
                <input class="form-control" asp-for="couleur" />
                <span asp-validation-for="couleur"></span>
            </div>

            <div class="form-group">
                <input class="btn btn-primary " type="submit" value="Chercher" />
            </div>

        </form>
    </div>
    <div class="col-md-8">
        @if (Model != null && Model.Trucks != null)
        {
            <div class="container">
                <div id="map"></div>
            </div>
            <script>
                var map;
                function initMap() {


                    map = new google.maps.Map(document.getElementById('map'), {
                        zoom: 14,
                        mapTypeId: 'satellite'

                    });
                    var contentString;
                    var markerlist = [];
                    var infowindowlist = [];
                    @foreach(var truck in Model.Trucks)
                    {
                        if (imarker == 0)
                        {
                            @:var center = new google.maps.LatLng(@truck.DerniereGeo.latitude, @truck.DerniereGeo.longitude);
                            @:map.panTo(center);
                        }
                            @:  markerlist[@imarker] = new google.maps.Marker({
                            @:  position: { lat: @truck.DerniereGeo.latitude, lng: @truck.DerniereGeo.longitude },
                            @:  map: map,
                            @:  });

                         @:contentString = '<div id="content"><div id="siteNotice"></div><div id="bodyContent"><h1 id="firstHeading" class=" text-center firstHeading">@truck.Id</h1><p>Emplacement <b>@truck.Emplacement</b>.</p><p>Couleur <b>@truck.Couleur</b>.</p><p>Batterie <b>@truck.NiveaudeBatterie</b>.</p><p>Firmware <b>@truck.FirmwareVersion</b>.</p><p>Date: <b>@truck.DerniereGeo.date.ToString()</b>.</p></div></div > ';

                        @:infowindowlist[@imarker] = new google.maps.InfoWindow({
                        @:    content: contentString
                        @:});
                        @:markerlist[@imarker].addListener('click', function () {
                        @:    infowindowlist[@imarker].open(map, markerlist[@imarker]);
                        @:});

                            imarker++;
                        }

                 }
            </script>
        }
    </div>
</div>

OuEstMonCamion/Views/FindTruck/Index.cshtml
@model OuEstMonCamion.Models.TruckModel
@{
    ViewData["Title"] = "Recherche";
    int imarker = 0;
    int zoom = 19;
    if (Model.detail)
    {
        zoom = 16;
    }
}

<br />
<br />
<br />
<br />
<div class="row " style="margin-left : 12px;">
    <div class="col-md-2">
        <form asp-action="Index" method="post">
            <div class="form-group">
                <label asp-for="RequestId"></label>
                <input class="form-control" asp-for="RequestId" />
                <span asp-validation-for="RequestId"></span>
            </div>


            <div class="form-check">
                <input type="checkbox" class="form-check-input" asp-for="detail">
                <label class="form-check-label" asp-for="detail">détails</label>
            </div>

            <div class="form-group">
                <input class="btn btn-primary " type="submit" value="Chercher" />
            </div>

        </form></div>
    <div class="col-md-8">
        @if (Model != null && !String.IsNullOrEmpty(Model.Id))
        {
            <div class="container">
                <div id="map"></div>
                </div>
                <script>
        var map;
        function initMap() {
            var truck1 = { lat: @Model.DerniereGeo.latitude, lng: @Model.DerniereGeo.longitude };


            var contentString = '<div id="content">' +
                '<div id="siteNotice">' +
                '</div>' +
                '<h1 id="firstHeading" class=" text-center firstHeading">@Model.Id</h1>' +
                '<div id="bodyContent">' +
                '<p>Emplacement <b>@Model.Emplacement</b>.</p>' +
                '<p>Couleur <b>@Model.Couleur</b>.</p>' +
                '<p>Batterie <b>@Model.NiveaudeBatterie</b>.</p>' +
                '<p>Firmware <b>@Model.FirmwareVersion</b>.</p>' +
                '</div>' +
                '</div>';

            

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            var flightPlanCoordinates = [
            @foreach (var coord in Model.GpsCoords)
            {
                @:{ lat: @coord.latitude, lng: @coord.longitude},

            }
            ];
            var flightPath = new google.maps.Polyline({
                path: flightPlanCoordinates,
                geodesic: true,
                strokeColor: '#FF0000',
                strokeOpacity: 1.0,
                strokeWeight: 3
            });




            map = new google.maps.Map(document.getElementById('map'), {
                center: truck1,
                zoom: @zoom,
                mapTypeId: 'satellite'

            });
            var marker = new google.maps.Marker({ position: truck1, map: map });

            infowindow.open(map, marker);
               marker.addListener('click', function () {
                    infowindow.open(map, marker);
                });

            @if (Model.detail) {
                    @:flightPath.setMap(map);
                }

            //vue detail
            var markerlist = [];
            var infowindowlist = [];
            var image = 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png';
            var imagepink = {
                url: 'http://maps.google.com/mapfiles/ms/icons/pink-dot.png',
                // This marker is 20 pixels wide by 32 pixels high.
                size: new google.maps.Size(50, 50),
                // The origin for this image is (0, 0).
                origin: new google.maps.Point(0, 0),
                // The anchor for this image is the base of the flagpole at (0, 32).
                anchor: new google.maps.Point(0, 32)
            };

             @if (Model.detail) {


             var query = Model.GpsCoords.OrderBy(x => x.date);
                var allButTheLastTwoElements = query.Take(query.Count() - 1);

             foreach (var coord in allButTheLastTwoElements)
             {

                     @:  markerlist[@imarker] = new google.maps.Marker({
                      @:  position: { lat: @coord.latitude, lng: @coord.longitude },
                      @:  map: map,

                    @if(imarker==0) {
                        @:icon: { url: 'http://maps.google.com/mapfiles/ms/micons/blue-pushpin.png' },
                    }
                    else {
                        @:icon: { url: 'http://maps.google.com/mapfiles/ms/micons/pink-pushpin.png' },
                    }
                  //  @: label: '@imarker'
                      @:     });

                     @:var contentString = '<div id="content"><div id="siteNotice"></div><div id="bodyContent"><p>Date: <b>@coord.date.ToString()</b>.</p></div></div>';

                    @:infowindowlist[@imarker] = new google.maps.InfoWindow({
                    @:    content: contentString
                    @:});
                    @:markerlist[@imarker].addListener('click', function () {
                    @:    infowindowlist[@imarker].open(map, markerlist[@imarker]);
                    @:});

            imarker++;
             }

        }

             }
                </script>
                }
            </div>
        </div>

    

OuEstMonCamion/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
@*<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>*@

OuEstMonCamion/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OuEstMonCamion/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>*@

OuEstMonCamion/Views/Shared/_Layout.cshtml
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OuEstMonCamion</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>
        /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
        #map {
            height: 100%;
            width: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        .battery:after {
            background-color: #fff;
            border: 2px solid #000;
            content: "";
            display: block;
            height: 16px;
            position: absolute;
            right: -6px;
            top: 6px;
            width: 6px;
        }

        .battery {
            background-color: #fff;
            border: 2px solid #000;
            height: 32px;
            margin-left: auto;
            margin-right: auto;
            position: relative;
            width: 100px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ParkMyTruck</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="FindTruck" asp-action="Index">Chercher</a></li>
                    <li><a asp-area="" asp-controller="FindTruck" asp-action="Details">Recherche Avancée</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="">
        @RenderBody()
        
       
        <hr />
        <footer>
            <p>&copy; 2018 - ParkMyTruck</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCA5jhb0-DD2ckOBgAELyfHnSBQKA9CVeU&callback=initMap"
            async defer></script>
</body>
</html>